version: '3.4'

services:
  reactapp:
    image: reactapp
    build:
      context: react-app
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
