"""made holdings its own model

Revision ID: b26b945a8e48
Revises: 8c1753ae95fd
Create Date: 2021-10-21 13:59:25.319872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b26b945a8e48'
down_revision = '8c1753ae95fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shares', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='holdings_stock_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='holdings_user_id_fkey')
    )
    # ### end Alembic commands ###
