"""made foreign keys non nullable

Revision ID: 051f384f035a
Revises: 2106dbc669d7
Create Date: 2021-10-28 22:23:03.808171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051f384f035a'
down_revision = '2106dbc669d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('holdings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('holdings', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watchlist_stocks', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watchlist_stocks', 'watchlist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlist_stocks', 'watchlist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('watchlist_stocks', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('holdings', 'stock_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('holdings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
